<?php
	$config['Company']['name'] = 'Sam\'s Telescopes';
	$config['Company']['slogan'] = 'Observe the Universe!';
	$config['Company']['phone'] = '555-55-55';
	$config['Image']['folder'] = 'img/products/';
	$config['Image']['cat_folder'] = 'img/categories/';
	$config['Image']['thumb_width'] = "150";
	$config['Image']['thumb_height'] = "100";
	$config['Image']['thumb_quality'] = "80";
	
	
	$config['Address']['states'] = array(
   "AL"=>"AL",
   "AK"=>"AK",
   "AZ"=>"AZ",
   "AR"=>"AR",
   "CA"=>"CA",
   "CO"=>"CO",
   "CT"=>"CT",
   "DE"=>"DE",
   "DC"=>"DC",
   "FL"=>"FL",
   "GA"=>"GA",
   "HI"=>"HI",
   "ID"=>"ID",
   "IL"=>"IL",
   "IN"=>"IN",
   "IA"=>"IA",
   "KS"=>"KS",
   "KY"=>"KY",
   "LA"=>"LA",
   "ME"=>"ME",
   "MD"=>"MD",
   "MA"=>"MA", 
   "MI"=>"MI",
   "MN"=>"MN",
   "MS"=>"MS",
   "MO"=>"MO",
   "MT"=>"MT",
   "NE"=>"NE",
   "NV"=>"NV",
   "NH"=>"NH",
   "NJ"=>"NJ",
   "NM"=>"NM",
   "NY"=>"NY",
   "NC"=>"NC",
   "ND"=>"ND",
   "OH"=>"OH",
   "OK"=>"OK",
   "OR"=>"OR",
   "PA"=>"PA",
   "RI"=>"RI",
   "SC"=>"SC",
   "SD"=>"SD",
   "TN"=>"TN",
   "TX"=>"TX",
   "UT"=>"UT",
   "VT"=>"VT",
   "VA"=>"VA",
   "WA"=>"WA",
   "WV"=>"WV",
   "WI"=>"WI",
   "WY"=>"WY");
?>